version: '3'

services:
    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#    kafka-topics-creator:
#      build:
#        context: kafka-topic-creator
#        dockerfile: Dockerfile
#      container_name: kafka-topics-creator
#      depends_on:
#        - zookeeper
#        - kafka